### PR TITLE
troubleshooting: make it a redirect

### PR DESCRIPTION
**Pull request by ES-Alexander**
Not sure if this is how I was supposed to do this. 

The `troubleshooting` directory only exists in the `gh-pages` branch, which is where Willian said the file needed to be replace. I changed the file to html and copied the existing format from Willian's previous 'make it a redirect' commits. 

I couldn't figure out how to serve this locally and check it from the `gh-pages` branch. I was getting an error of `FileNotFoundError: No "README" file (or is ignored)`, so tried adding a blank readme (not commited) which then served blank docs with only the default tabs down the side and none of our content.

From what I can tell, this is the final consolidation of #160, and the original issue there has already been solved (both the new and replaced troubleshooting page have the same `Reset MavProxy Options` section.

### CODE REVIEW

**Comment by Williangalvani** [comment]
This looks correct!
The readme issue is because we're not really supposed to touch this branch, we're dealing with some stale pages that were left over from previous runs. The right way to test it would probably be just running a ´python -m http.server´ since these are the "built" files.

**Review by Williangalvani — APPROVED** [review]

**Comment by Williangalvani** [comment]
I believe there's a couple more to do, but let's merge this one as a test.

**Comment by ES-Alexander** [comment]
I'll see if I can have a bit of a sleuth for extra ones tomorrow :-)

**Comment by Williangalvani** [comment]
thanks! I think you can easily spot them by looking for .md files in the gh-pages branch

**Pull request merged**
