### PR TITLE
Pymavlink updates

### PR DESCRIPTION
**Pull request by ES-Alexander**
- [x] add hyperlinked shortcuts (ToC) to make examples easier to navigate
- [x] add sending message to QGC example (#159)
- [x] add setting target depth in depth-hold mode example (#195)
- [x] update arm-disarm example to include arming check and confirmation waits
- [ ] add input hold example (#132)
- [x] add `set_attitude_hold` in depth-hold mode example (#131)
- [x] add gripper example (#128) (possibly with `MAV_CMD_DO_SET_SERVO`)

### CODE REVIEW

**Comment by ES-Alexander** [comment]
Not sure if there's example code somewhere for the last two, or if they were something that @patrickelectric was planning to write at some point. If they're not available and not easy to make then this can just be merged as is :-)

**Comment by ES-Alexander** [comment]
Not sure about input hold, but should be able to create examples for the gripper and attitude tomorrow.

**Review by patrickelectric — COMMENTED** [review]
The patch looks great, just some minor corrections and organization to get it merged.
One important point is to squash the necessary changes in the specific commits, for that, I recommend the following links (I just did a quick google search):
https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d
https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by ES-Alexander** [comment]
@patrickelectric 
Ended up being easier to just `reset --soft` and recreate the commit messages manually since there were multiple sets of separated commits that I needed to squash. Incorporated all your suggestions, so should hopefully be good to merge now :-)

**Review by patrickelectric — APPROVED** [review]

**Comment by ES-Alexander** [comment]
Can this be merged? 

Not sure if @jaxxzer or @Williangalvani are wanting to review or something, but I don’t have merge permission so someone else will need to merge it.

**Review by Williangalvani — APPROVED** [review]
Nice. Great job!

**Pull request merged**
