### PR TITLE
Take altimeters page out while we improve support for it

### PR DESCRIPTION
**Pull request by Williangalvani**

### CODE REVIEW

**Comment by patrickelectric** [comment]
So.. It looks like that problem is not the altimeter page but the content, to me, it appears that we should fix the page content and not remove it.
Can you explain it a bit better in your commit body or in this PR ? The apparent problem vs the proposed solution is not clear.

**Comment by Williangalvani** [comment]
Altimeters are currently not supported in Ardusub 3.5 nor 4.0.
This page explains how to setup it, which may lead people to fruitlessly try to set this up.

**Comment by patrickelectric** [comment]
It appears better to remove also the page, to avoid any changes to the user to find it via search engines or something else.

**Comment by patrickelectric** [comment]
Please, don't forget to update the commit body to explain it.

**Comment by Williangalvani** [comment]
@patrickelectric updated

**Pull request merged**
